[pytest]
base_url = https://automationexercise.com
pythonpath = .
testpaths = tests
addopts = --html=reports/report.html --self-contained-html --screenshot=on --video=on --tracing=on --output=evidencias